### ISSUE TITLE
 not found

### ISSUE THREAD

**Issue by qrpengx** [krejcmat/hadoop-hbase-docker#1]
Pulling repository docker.io/krejcmat/hadoop-hbase-master
Tag latest not found in repository docker.io/krejcmat/hadoop-hbase-master

**Comment by krejcmat** [comment]
Please try it now. Triggers on Docker hub was disabled due to working on project.  Currently two versions are available:
`docker pull krejcmat/hadoop-hbase-master:latest`
which is compiled on Docker Hub from github sources
and
`docker pull krejcmat/hadoop-hbase-master:0.1
`
which should be stable.
